<a href="https://colab.research.google.com/github/fralfaro/MAT281_2023/blob/main/docs/labs/lab_031.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# MAT281 - Laboratorio N°03

## Problema 01


<img src="https://imagenes.universia.net/gc/net/images/practicas-empleo/p/pr/pro/profesiones-con-el-avance-de-la-tecnologia.jpg" width="480" height="360" align="center"/>


EL conjunto de datos se denomina `ocupation.csv`, el cual contiene información de distintos usuarios (edad ,sexo, profesión, etc.).

Lo primero es cargar el conjunto de datos y ver las primeras filas que lo componen:

In [4]:
import pandas as pd

In [3]:
# load data
url='https://drive.google.com/file/d/1SW1_vWBLd50COj4FbQdZenqAwA0nLDqC/view?usp=drive_link'
url='https://drive.google.com/uc?id=' + url.split('/')[-2]

df = pd.read_csv(url, sep="|" )
df.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

El objetivo es tratar de obtener la mayor información posible de este conjunto de datos. Para cumplir este objetivo debe resolver las siguientes problemáticas:

1.- ¿Cuál es el número de observaciones en el conjunto de datos?

In [25]:
# número de observaciones
num_obs = df.shape[0]
print("\nel número de observaciones es:", num_obs)

el número de observaciones es: 943

2.- ¿Cuál es el número de columnas en el conjunto de datos?

In [11]:
# número de columnas
num_col = df.shape[1]
print("\nel núemero de columnas es:", num_col)

el núemero de columnas es: 5

3.- Imprime el nombre de todas las columnas

In [15]:
# nombre de columnas
col_names = df.columns
print("\nLos nombres de las columnas son:")
for col in col_names:
  print(col)

Los nombres de las columnas son:
user_id
age
gender
occupation
zip_code

4.- Imprima el índice del dataframe

In [18]:
# indice del dataframe
index_dataframe = df.index
print("\nel índice del dataframe es:", index_dataframe)

el índice del dataframe es: RangeIndex(start=0, stop=943, step=1)

5.- ¿Cuál es el tipo de datos de cada columna?

In [29]:
# tipo de dato columnas
type_df = df.dtypes
print("\n El tipo de dato de cada columna es:\n", type_df)

 El tipo de dato de cada columna es:
 user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

6.- Describir el conjunto de datos (**hint**: .describe())

In [98]:
# Descripción del conjunto de datos
desc = df.describe(include = 'all')
print("\nLa descripción para la dataframe es:\n")
desc

La descripción para la dataframe es:

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

**Nota**: Dado el tipo de dato que tiene cada columna, no es posible obtener medidas de tendencia central para el campo "gender" y el campo "occupation".

7.- Imprimir solo la columna de **occupation**.

In [66]:
# Imprimir columna "ocupación"
occupation_col = df['occupation'].reset_index()
occupation_col = occupation_col.drop(['index'], axis=1)
print("\nLa columna 'occupation' es:\n")
occupation_col

La columna 'occupation' es:

        occupation
0       technician
1            other
2           writer
3       technician
4            other
..             ...
938        student
939  administrator
940        student
941      librarian
942        student

[943 rows x 1 columns]

8.- ¿Cuántas ocupaciones diferentes hay en este conjunto de datos?

In [49]:
# Número de ocupaciones
num_occupation = df['occupation'].nunique()
print("\nEl número de ocupaciones diferentes es:", num_occupation)

El número de ocupaciones diferentes es: 21

9.- ¿Cuál es la ocupación más frecuente?

In [83]:
# Ocupación más frecuente
occupation_count = df['occupation'].value_counts()
freq_occupations = occupation_count.loc[occupation_count == occupation_count.max()]
if len(freq_occupations) > 1:
    print("\nLas ocupaciones más frecuentes con un total de:", occupation_count[0], "persona(s) por ocupación, son:\n", freq_occupations)
else:
    print("\nLa ocupación más frecuente es:", occupation_count.index[0],", con un total de:", occupation_count[0])

La ocupación más frecuente es: student , con un total de: 196

10.- ¿Cuál es la edad media de los usuarios?

In [53]:
# Edad media de los usuarios
age_mean = df['age'].mean()
print("\nLa edad media de los usuarios es:", int(age_mean))

La edad media de los usuarios es: 34

**Nota**: En este caso, se ha decidido optar por aproximar al entero más cercano dada la naturaleza de los datos, pues el campo 'age' es del tipo entero.

11.- ¿Cuál es la edad con menos ocurrencia?

In [94]:
# Edad con menos ocurrencia
age_counts = df['age'].value_counts()
freq_age = age_counts.loc[age_counts == age_counts.min()]
if len(freq_age) > 1:
    print("\nLas edades menos frecuentes, con un total de", age_counts.min(), "persona(s) por edad, son:\n", freq_age)
else:
    print("\nLa edad menos frecuente es:", freq_age,", con un total de:", freq_age)

Las edades menos frecuentes, con un total de 1 persona(s) por edad, son:
 7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64